apiVersion: v1
data:
<<<<<<< HEAD
  actions.cli: "
    embed-server --std-out=echo --server-config=standalone-openshift.xml

    batch

    set DB_USERNAME=$DB_USERNAME
    set DB_PASSWORD=$DB_PASSWORD
    set DB_JDBC_URL=$DB_JDBC_URL
    set DB_DRIVER_NAME=$DRIVER_NAME
    set DB_DRIVER=oracle.jdbc.OracleDriver
    set DB_XA_DRIVER=oracle.jdbc.xa.client.OracleXADataSource
    set DB_EAP_MODULE=com.oracle
    set FILE=/opt/eap/extensions/ojdbc8-12.2.0.1.0.jar

    module add --name=com.oracle --resources=/opt/eap/extensions/ojdbc8-12.2.0.1.0.jar --dependencies=javax.api,javax.resource.api

    /subsystem=datasources/jdbc-driver=oracle:add( \
        driver-name=oracle, \
        driver-module-name=com.oracle, \
        driver-xa-datasource-class-name=oracle.jdbc.xa.client.OracleXADataSource \
    )

    /subsystem=datasources/data-source=KeycloakDS:remove()

    /subsystem=datasources/data-source=KeycloakDS:add( \
        jndi-name=java:jboss/datasources/KeycloakDS, \
        enabled=true, \
        use-java-context=true, \
        connection-url=jdbc:oracle:thin:@10.170.95.243:1521/PWIPRE, \
        driver-name=oracle, \
        user-name=sys, \
        password=tstkZxSHIDpMqVSv \
    )"
=======
  actions.cli: "embed-server --std-out=echo --server-config=standalone-openshift.xml\n\necho
    \" ---------- CUSTOM CONFIGURACION ----------\" \necho \" -- Check 'Database info'
    string on logs! --\"\n\n# /subsystem=logging/root-logger=ROOT:write-attribute(name=level,
    value=\"DEBUG\")\n\nbatch\n\nset DB_USERNAME=C##ADMIN\nset DB_PASSWORD=redhat01\nset
    DB_JDBC_URL=jdbc:oracle:thin:@10.131.0.86:1521/ABC\n\nset DB_DRIVER_NAME=oracle\nset
    DB_DRIVER=oracle.jdbc.OracleDriver\nset DB_XA_DRIVER=oracle.jdbc.xa.client.OracleXADataSource\nset
    DB_EAP_MODULE=com.oracle\nset FILE=/opt/eap/extensions/ojdbc8-12.2.0.1.0.jar\nset
    DEPENDENCIES=javax.api,javax.resource.api\nset JNDI_NAME=java:jboss/datasources/KeycloakDS\n\nmodule
    add --name=$DB_EAP_MODULE --resources=$FILE --dependencies=$DEPENDENCIES\n\n/subsystem=datasources/jdbc-driver=oracle:add(driver-name=$DB_DRIVER_NAME,
    driver-module-name=$DB_EAP_MODULE, driver-xa-datasource-class-name=$DB_XA_DRIVER)\n\n/subsystem=datasources/data-source=KeycloakDS:remove()\n\n/subsystem=datasources/data-source=KeycloakDS:add(jndi-name=$JNDI_NAME,
    enabled=true, use-java-context=true, connection-url=$DB_JDBC_URL, driver-name=$DB_DRIVER_NAME,
    user-name=$DB_USERNAME, password=$DB_PASSWORD)\n\necho \"  ---------- CONFIGURATION
    APPLIED! ----------\" \n\nrun-batch\n\nquit"
immutable: false
>>>>>>> b8a2ad4a7eff7be170ecc9628512e728007ab71c
kind: ConfigMap
metadata:
  labels:
    application: sso
<<<<<<< HEAD
  name: actions-cli-cm
=======
  name: actions-cli-cm
>>>>>>> b8a2ad4a7eff7be170ecc9628512e728007ab71c
