---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: keycloak-db-secret
  #name: {{ .Release.Name }}-db-secret
  namespace: {{ .Release.Namespace }}
stringData:
  POSTGRES_DATABASE: {{ .Values.secret.postgres_database }}
  POSTGRES_USERNAME: {{ .Values.secret.postgres_username }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgres_password }}
  POSTGRES_EXTERNAL_ADDRESS: {{ .Values.secret.postgres_external_address }}
  POSTGRES_EXTERNAL_PORT: '5432'
  #POSTGRES_EXTERNAL_PORT: {{ .Values.secret.postgres_external_port }}
