---
subscription:
  name: rhsso-operator
  #namespace: rhsso-dev
  namespace: "rhn-gps-splatas-dev"
  startingCSV: rhsso-operator.7.6.1-opr-005

secret:
  postgres_database: "CHANGE_ME"
  postgres_username: "CHANGE_ME"
  postgres_password: "CHANGE_ME"
  postgres_external_address: "CHANGE_ME"
  postgres_external_port: "CHANGE_ME"

keycloak:
  name: rhsso-dev
  #namespace: rhsso-dev
  namespace: "rhn-gps-splatas-dev"
  disableReplicasSyncing: true
  multiAvailablityZones:
    enabled: true
  externalAccess:
    enabled: true
  externalDatabase:
    enabled: true
  keycloakDeploymentSpec:
    imagePullPolicy: Always
  postgresDeploymentSpec:
    imagePullPolicy: Always
  instances: 1
  storageClassName: gp2

hpa:
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50
  averageUtilization: 50
