#apiVersion: v1 
#kind: Secret 
#metadata: 
#  annotations:
#    argocd.argoproj.io/sync-wave: "1"
#  name: keycloak-db-secret 
#  namespace: rhsso-sandbox
#stringData: 
#  POSTGRES_DATABASE: "pgsql-rhsso-sandbox"
#  POSTGRES_USERNAME: "pgsql-admin"
#  POSTGRES_PASSWORD: "pgsql-password"
#  POSTGRES_EXTERNAL_ADDRESS: "172.30.204.89"
#  POSTGRES_EXTERNAL_PORT: "5432"
---
apiVersion: v1 
kind: Secret 
metadata: 
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: keycloak-db-secret 
  namespace: rhsso-sandbox
stringData: 
  POSTGRES_DATABASE: "keycloak"
  POSTGRES_USERNAME: "rosa"
  POSTGRES_PASSWORD: "inBeNlZ[PSNsCEih"
  POSTGRES_EXTERNAL_ADDRESS: "a-snb-rosa-01.crezaon8byla.eu-central-1.rds.amazonaws.com"
  POSTGRES_EXTERNAL_PORT: "5432"
