apiVersion: v1 
kind: Secret 
metadata: 
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: keycloak-db-secret 
  namespace: rhsso-prod
stringData: 
  POSTGRES_DATABASE: "pgsql-rhsso-prod"
  POSTGRES_USERNAME: "pgsql-admin"
  POSTGRES_PASSWORD: "pgsql-password"
  POSTGRES_EXTERNAL_ADDRESS: "172.30.204.89"
  POSTGRES_EXTERNAL_PORT: "5432"