---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: rhsso-dev
  labels:
    app: rhsso-dev
  namespace: rhsso-dev
spec:
  multiAvailablityZones:
    enabled: true
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    imagePullPolicy: Always
  postgresDeploymentSpec:
    imagePullPolicy: Always
  instances: 2
  storageClassName: gp2